name: build

on:
  push

jobs:
  check:
    name: Run Checks
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set rustup profile
        run: rustup set profile minimal

      - name: Install Rust toolchain
        run: rustup toolchain install stable

      - name: Get timestamp for cache
        id: date
        run: echo ::set-output name=yearmo::$(date +%Y%m)
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry/index
          key: cargo-registry-index-${{steps.date.outputs.yearmo}}

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Debug build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
